name: Publish to GitHub Pages
on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
concurrency:
  group: github-pages
  cancel-in-progress: false
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    env:
      BUNDLE_GEMFILE: .doc/Gemfile
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configure Pages
      id: pages
      uses: actions/configure-pages@v3
    - name: Install node
      uses: actions/setup-node@v5
      with:
        node-version: 22
    - name: Install mermaid
      run: npm install -g @mermaid-js/mermaid-cli
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
        cache-version: 1
    - name: prep site directory
      run: mkdir -p _site && cp -r doc_images _site/
    - name: Generate README
      run: bundle exec asciidoctor -r asciidoctor-diagram -a mermaid-puppeteer-config=.doc/puppeteer.config.json -a docinfodir=.doc -a docinfo=shared README.adoc -o _site/index.html
    - name: Generate RUNNING
      run: bundle exec asciidoctor -r asciidoctor-diagram -a mermaid-puppeteer-config=.doc/puppeteer.config.json -a docinfodir=.doc -a docinfo=shared RUNNING.adoc -o _site/RUNNING.html
    - name: Create docs/adr directory
      run: mkdir -p _site/docs/adr
    - name: Generate ADR Index (Root)
      run: bundle exec asciidoctor -r asciidoctor-diagram -a mermaid-puppeteer-config=.doc/puppeteer.config.json -a docinfodir=.doc -a docinfo=shared docs/index.adoc -o _site/docs/adr/index.html
    - name: Generate ADR-0001
      run: bundle exec asciidoctor -r asciidoctor-diagram -a mermaid-puppeteer-config=.doc/puppeteer.config.json -a docinfodir=.doc -a docinfo=shared docs/adr/0001-use-ipv6-addressing.adoc -o _site/docs/adr/0001-use-ipv6-addressing.html
    - name: Generate ADR-0002
      run: bundle exec asciidoctor -r asciidoctor-diagram -a mermaid-puppeteer-config=.doc/puppeteer.config.json -a docinfodir=.doc -a docinfo=shared docs/adr/0002-use-mem-etcd-instead-of-standard-etcd.adoc -o _site/docs/adr/0002-use-mem-etcd-instead-of-standard-etcd.html
    - name: Generate ADR-0003
      run: bundle exec asciidoctor -r asciidoctor-diagram -a mermaid-puppeteer-config=.doc/puppeteer.config.json -a docinfodir=.doc -a docinfo=shared docs/adr/0003-implement-distributed-scheduler.adoc -o _site/docs/adr/0003-implement-distributed-scheduler.html
    - name: Generate ADR Template
      run: bundle exec asciidoctor -r asciidoctor-diagram -a mermaid-puppeteer-config=.doc/puppeteer.config.json -a docinfodir=.doc -a docinfo=shared docs/adr/template.adoc -o _site/docs/adr/template.html
    - name: Generate ADR-MASTER
      run: bundle exec asciidoctor -r asciidoctor-diagram -a mermaid-puppeteer-config=.doc/puppeteer.config.json -a docinfodir=.doc -a docinfo=shared docs/adr/ADR-MASTER.adoc -o _site/docs/adr/ADR-MASTER.html
    - name: Upload Artifacts
      uses: actions/upload-pages-artifact@v3
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4